### Send POST request with json body
POST http://localhost/v1/convert/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTYyNjYyODk5OCwiaWF0IjoxNjI2NjI4OTk4fQ.KxWrqWFxqwZ4Km0WfV8nlnGvX7GiORdgdpwG0fz4wWgeyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkFkbWluIiwiZXhwIjoxNjU4MTY0OTk4LCJpYXQiOjE2MjY2Mjg5OTh9.MRv8_dUv5a3JGtVMX4ORkU4I5pfcP939i-Sff4Mszcc

{
  "currency_from": "RUB",
  "currency_to": "USD",
  "value": 100
}

